// http_client/src-tauri/src/desktop/tray.rs
use tauri::{
    image::Image,
    include_image,
    menu::{Menu, MenuEvent, MenuItem},
    tray::TrayIconBuilder,
    App, AppHandle, Runtime,
};

use super::window::{report_window_error, show_main_window, EXIT_CODE_SUCCESS};

const TRAY_ID: &str = "main-tray";
const MENU_ID_SHOW: &str = "show";
const MENU_ID_QUIT: &str = "quit";

/// The notification area draws icons at 16 px times the display scale. The
/// bundle icon is drawn for large sizes, where a gradient and soft corners
/// work; the tray gets the small-size build instead (flat plate, larger
/// glyph), generated by tools/build-installer-art.py.
const TRAY_BASE_SIZE: f64 = 16.0;
/// Smallest first. Embedded as pixels, which is why the list stops at 48.
static TRAY_ICONS: [(u32, Image<'static>); 6] = [
    (16, include_image!("icons/tray-16.png")),
    (20, include_image!("icons/tray-20.png")),
    (24, include_image!("icons/tray-24.png")),
    (32, include_image!("icons/tray-32.png")),
    (40, include_image!("icons/tray-40.png")),
    (48, include_image!("icons/tray-48.png")),
];
/// Assumed when the primary monitor cannot be read.
const DEFAULT_SCALE: f64 = 1.0;

/// The bus names a StatusNotifier tray host owns: KDE Plasma, and GNOME with
/// the AppIndicator extension, own the first; the second is the newer
/// freedesktop spelling of the same service.
#[cfg(target_os = "linux")]
const TRAY_HOST_NAMES: [&str; 2] = [
    "org.kde.StatusNotifierWatcher",
    "org.freedesktop.StatusNotifierWatcher",
];

/// Makes the tray icon, if this desktop can show one.
///
/// Stock GNOME, which Fedora Workstation uses, has no tray (PLAN-LINUX.md
/// F3). libappindicator then falls back to GTK's old GtkStatusIcon, which has
/// nowhere to draw either and logs `gtk_widget_get_scale_factor` criticals at
/// startup (found in 17a, traced with G_DEBUG=fatal-criticals). So on Linux
/// the icon is made only when a tray host is running. A host that starts
/// later is picked up on the next launch.
///
/// Returns whether there is a tray, which decides what the close button does
/// (desktop/window.rs).
pub fn build_tray<R: Runtime>(app: &App<R>) -> tauri::Result<bool> {
    if !tray_host_available() {
        log::info!("tray: this desktop has no tray host; running without a tray icon");
        return Ok(false);
    }

    let show = MenuItem::with_id(app, MENU_ID_SHOW, "Show", true, None::<&str>)?;
    let quit = MenuItem::with_id(app, MENU_ID_QUIT, "Quit", true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&show, &quit])?;

    let mut builder = TrayIconBuilder::with_id(TRAY_ID)
        .tooltip("ResponderHTTP")
        .menu(&menu)
        .on_menu_event(handle_menu_event);

    // The tray sits on the primary monitor's taskbar, so that is the scale
    // to draw for. A scale change while running is left to the shell, which
    // resizes the icon it already has.
    let scale = app
        .primary_monitor()
        .ok()
        .flatten()
        .map_or(DEFAULT_SCALE, |monitor| monitor.scale_factor());
    builder = builder.icon(tray_icon(scale).clone());

    builder.build(app)?;
    Ok(true)
}

/// Windows always has a notification area.
#[cfg(not(target_os = "linux"))]
fn tray_host_available() -> bool {
    true
}

/// Whether a StatusNotifier host owns its name on the session bus. A bus that
/// cannot be asked is logged and counts as no host: libappindicator would
/// find nothing to show the icon on either.
#[cfg(target_os = "linux")]
fn tray_host_available() -> bool {
    match linux_tray_host() {
        Ok(found) => found,
        Err(error) => {
            log::warn!("tray: could not ask the session bus for a tray host: {error}");
            false
        }
    }
}

#[cfg(target_os = "linux")]
fn linux_tray_host() -> zbus::Result<bool> {
    let connection = zbus::blocking::Connection::session()?;
    let bus = zbus::blocking::fdo::DBusProxy::new(&connection)?;
    for name in TRAY_HOST_NAMES {
        if bus.name_has_owner(zbus::names::BusName::try_from(name)?)? {
            return Ok(true);
        }
    }
    Ok(false)
}

/// The smallest drawn size that is at least as large as the shell will show,
/// so the icon is only ever scaled down, never blown up — by four pixels at
/// most (175 % wants 28 and gets 32).
fn tray_icon_size(scale: f64) -> u32 {
    let wanted = (TRAY_BASE_SIZE * scale).ceil();
    TRAY_ICONS
        .iter()
        .map(|(size, _)| *size)
        .find(|size| f64::from(*size) >= wanted)
        .unwrap_or(TRAY_ICONS[TRAY_ICONS.len() - 1].0)
}

fn tray_icon(scale: f64) -> &'static Image<'static> {
    let size = tray_icon_size(scale);
    TRAY_ICONS
        .iter()
        .find(|(candidate, _)| *candidate == size)
        .map(|(_, image)| image)
        .unwrap_or(&TRAY_ICONS[0].1)
}

fn handle_menu_event<R: Runtime>(app: &AppHandle<R>, event: MenuEvent) {
    match event.id().as_ref() {
        MENU_ID_SHOW => {
            if let Err(err) = show_main_window(app) {
                report_window_error("show main window", &err);
            }
        }
        MENU_ID_QUIT => app.exit(EXIT_CODE_SUCCESS),
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn each_windows_scale_step_gets_a_size_at_least_as_large() {
        for (scale, expected) in [
            (1.0, 16),
            (1.25, 20),
            (1.5, 24),
            (1.75, 32),
            (2.0, 32),
            (2.25, 40),
            (2.5, 40),
            (3.0, 48),
        ] {
            assert_eq!(tray_icon_size(scale), expected, "scale {scale}");
        }
    }

    #[test]
    fn scales_outside_the_drawn_range_use_the_nearest_end() {
        assert_eq!(tray_icon_size(0.5), 16);
        assert_eq!(tray_icon_size(4.0), 48);
        assert_eq!(tray_icon_size(f64::NAN), 48);
    }

    #[test]
    fn every_embedded_icon_is_square_and_the_size_it_claims() {
        for (size, image) in &TRAY_ICONS {
            assert_eq!((image.width(), image.height()), (*size, *size));
            assert_eq!(image.rgba().len(), (*size * *size * 4) as usize);
        }
    }

    /// Claims the tray-host name itself, so it needs a bus of its own: on a
    /// desktop with a real tray the name is taken, and on one without it the
    /// test would briefly pretend to be a tray. Run by
    /// tools/test-linux-session.sh inside `dbus-run-session`.
    #[cfg(target_os = "linux")]
    #[test]
    #[ignore = "claims a session bus name: run tools/test-linux-session.sh"]
    fn a_tray_host_is_seen_only_while_its_name_is_owned() {
        assert!(!linux_tray_host().expect("the bus answers"));

        let host = zbus::blocking::connection::Builder::session()
            .and_then(|builder| builder.name(TRAY_HOST_NAMES[0]))
            .and_then(|builder| builder.build())
            .expect("the name can be claimed on a private bus");
        assert!(linux_tray_host().expect("the bus answers"));

        drop(host);
        assert!(!linux_tray_host().expect("the bus answers"));
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn every_tray_host_name_is_a_valid_bus_name() {
        for name in TRAY_HOST_NAMES {
            assert!(zbus::names::BusName::try_from(name).is_ok(), "{name}");
        }
    }

    #[test]
    fn the_icon_returned_matches_the_size_chosen() {
        for scale in [1.0, 1.5, 2.0, 3.0] {
            assert_eq!(tray_icon(scale).width(), tray_icon_size(scale));
        }
    }
}
